---
title: "IP2038 Assessment"
<<<<<<< HEAD
format: pdf
=======
format: 
  html:
    toc: true
    toc-location: left
    embed-resources: true
>>>>>>> 79093ac (Updated files)
editor: visual
execute:
  echo: true
  output: true
  messages: false
  warning: false
---

<!-- More information on how to complete the different components of the assignment at https://stefanopagliari.info/Notes/IP2038+Assessment+Guidance+2022-23 -->

# 1. Summary of the Selected Indicator
<<<<<<< HEAD

<!-- Approx 300-400 words + 1 visualization or summary table-->

=======
<!-- Approx 300-400 words + 1 visualization or summary table-->

 

>>>>>>> 79093ac (Updated files)
```{r 1.A Code Chunk}
#Load packages
library(tidyverse)

#Download the csv file


```

<<<<<<< HEAD
------------------------------------------------------------------------

# 2. Across Countries Comparison

=======
 

------------------------------------------------------------------------

# 2. Across Countries Comparison
>>>>>>> 79093ac (Updated files)
<!-- Approx 300-400 words + 1 visualization -->

```{r 2.A Code Chunk}
 

```

<<<<<<< HEAD
------------------------------------------------------------------------

# 3. Across Time Analysis

=======
 

------------------------------------------------------------------------

# 3. Across Time Analysis
>>>>>>> 79093ac (Updated files)
<!-- Approx 300-400 words + 1 visualization-->

```{r 3.A Code Chunk}
  

 
```

<<<<<<< HEAD
------------------------------------------------------------------------

# 4. Association With Other Economic or Political Factors.

=======


------------------------------------------------------------------------

# 4. Association With Other Economic or Political Factors.
>>>>>>> 79093ac (Updated files)
<!-- Approx 300-400 words + 1 visualization-->

```{r 4.A Code Chunk}



```

<<<<<<< HEAD
------------------------------------------------------------------------

# 5 Conclusion: what have we learnt through the analysis of this data?

<!-- Approx 200-300 words-->
=======
 

------------------------------------------------------------------------

# 5 Conclusion: what have we learnt through the analysis of this data? 
<!-- Approx 200-300 words-->

>>>>>>> 79093ac (Updated files)
